version: '3'
services:
  app:
    build: .
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DATABASE_URL="postgres://root:password@db:5432/users"
      - DB_NAME=users
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - db # runs first
  
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: