version: '3'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=7000
      - NODE_ENV=development
      - DB_NAME=usersDev
      - DB_USER=root
      - DB_PASSWORD=password
    # env_file:
    #   - ./.env
    command: npm run dev
  
  db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=usersDev
    

